/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uas_mahasiswa;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        nilaiNKEditField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        DeleteButtonNK = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        npmNKEditField = new javax.swing.JTextField();
        npmSearchField1 = new javax.swing.JTextField();
        kodeKuliahNKEditField = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        UpdateButtonNK = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        traversalNilaiKuliah = new javax.swing.JTable();
        KKSearchField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        kodeKuliahNKInputField = new javax.swing.JTextField();
        nilaiNKInputField = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        insertInputNKButton = new javax.swing.JButton();
        resetInputNKButton = new javax.swing.JButton();
        npmNKInputField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        kodeKuliahEditField = new javax.swing.JTextField();
        npmSearchField2 = new javax.swing.JTextField();
        sksEditField = new javax.swing.JTextField();
        namaKuliahEditField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        searchButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        semesterEditField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        UpdateKButton = new javax.swing.JButton();
        DeleteKButton = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        traversalKuliah = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        npmEditField = new javax.swing.JTextField();
        namaEditField = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        npmSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jkEditField = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        tglLhrEditField = new javax.swing.JTextField();
        alamatEditField = new javax.swing.JTextField();
        noTelpEditField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        traversalMahasiswa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        insertInputButton = new javax.swing.JButton();
        resetInputButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        npmInputField = new javax.swing.JTextField();
        namaInputField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jkInputField = new javax.swing.JTextField();
        tglLhrInputField = new javax.swing.JTextField();
        alamatInputField = new javax.swing.JTextField();
        noTelpInputField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        insertInputButton1 = new javax.swing.JButton();
        resetInputButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        sksInputField = new javax.swing.JTextField();
        namaKuliahInputField = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        semesterInputField = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        kodeKuliahInputField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 190, 0));

        nilaiNKEditField.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(37, 24, 46));
        jLabel14.setText("Search data");

        jLabel15.setForeground(new java.awt.Color(37, 24, 46));
        jLabel15.setText("NPM :");

        jLabel16.setForeground(new java.awt.Color(37, 24, 46));
        jLabel16.setText("Kode Kuliah :");

        jLabel32.setForeground(new java.awt.Color(37, 24, 46));
        jLabel32.setText("Nilai :");

        DeleteButtonNK.setBackground(new java.awt.Color(202, 31, 61));
        DeleteButtonNK.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButtonNK.setText("Delete");
        DeleteButtonNK.setEnabled(false);
        DeleteButtonNK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonNKActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(37, 24, 46));
        jLabel33.setText("Result data");

        jLabel34.setForeground(new java.awt.Color(37, 24, 46));
        jLabel34.setText("NPM");

        npmNKEditField.setEditable(false);
        npmNKEditField.setEnabled(false);
        npmNKEditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npmNKEditFieldActionPerformed(evt);
            }
        });

        npmSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npmSearchField1ActionPerformed(evt);
            }
        });

        kodeKuliahNKEditField.setEnabled(false);

        searchButton1.setBackground(new java.awt.Color(51, 153, 0));
        searchButton1.setForeground(new java.awt.Color(255, 255, 255));
        searchButton1.setText("Search");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        UpdateButtonNK.setBackground(new java.awt.Color(202, 31, 61));
        UpdateButtonNK.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButtonNK.setText("Update");
        UpdateButtonNK.setEnabled(false);
        UpdateButtonNK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonNKActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(37, 24, 46));
        jLabel44.setText("Traversal");

        traversalNilaiKuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "NPM", "Kode Kuliah", "Nilai"
            }
        ));
        traversalNilaiKuliah.setEnabled(false);
        jScrollPane6.setViewportView(traversalNilaiKuliah);

        KKSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KKSearchFieldActionPerformed(evt);
            }
        });

        jLabel42.setForeground(new java.awt.Color(37, 24, 46));
        jLabel42.setText("Kode Kuliah");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nilaiNKEditField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeKuliahNKEditField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npmNKEditField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addComponent(jLabel20)
                        .addContainerGap(509, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel33)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KKSearchField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(npmSearchField1))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButtonNK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteButtonNK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel44)
                                .addGap(183, 183, 183))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(searchButton1)
                                    .addComponent(DeleteButtonNK)
                                    .addComponent(UpdateButtonNK)
                                    .addComponent(npmSearchField1))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(KKSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(npmNKEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(kodeKuliahNKEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(nilaiNKEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                .addGap(110, 110, 110))
        );

        jTabbedPane1.addTab("NIlai Kuliah", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 190, 0));

        kodeKuliahNKInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeKuliahNKInputFieldActionPerformed(evt);
            }
        });

        jLabel47.setForeground(new java.awt.Color(37, 24, 46));
        jLabel47.setText("NPM :");

        jLabel50.setForeground(new java.awt.Color(37, 24, 46));
        jLabel50.setText("Kode Kuliah :");

        jLabel51.setForeground(new java.awt.Color(37, 24, 46));
        jLabel51.setText("Nilai :");

        jLabel52.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(37, 24, 46));
        jLabel52.setText("Input data Nilai Kuliah");

        insertInputNKButton.setBackground(new java.awt.Color(0, 51, 255));
        insertInputNKButton.setForeground(new java.awt.Color(255, 255, 255));
        insertInputNKButton.setText("Insert");
        insertInputNKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertInputNKButtonActionPerformed(evt);
            }
        });

        resetInputNKButton.setBackground(new java.awt.Color(202, 31, 61));
        resetInputNKButton.setForeground(new java.awt.Color(255, 255, 255));
        resetInputNKButton.setText("Reset");
        resetInputNKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetInputNKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel52))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nilaiNKInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(kodeKuliahNKInputField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(insertInputNKButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetInputNKButton))
                            .addComponent(npmNKInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel52)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(npmNKInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(kodeKuliahNKInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(nilaiNKInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertInputNKButton)
                    .addComponent(resetInputNKButton))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Tambah Nilai Kuliah", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 190, 0));

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(37, 24, 46));
        jLabel35.setText("Result data");

        jLabel36.setForeground(new java.awt.Color(37, 24, 46));
        jLabel36.setText("NPM");

        kodeKuliahEditField.setEditable(false);
        kodeKuliahEditField.setEnabled(false);

        npmSearchField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npmSearchField2ActionPerformed(evt);
            }
        });

        sksEditField.setEnabled(false);

        namaKuliahEditField.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(37, 24, 46));
        jLabel19.setText("Search data");

        searchButton2.setBackground(new java.awt.Color(51, 153, 0));
        searchButton2.setForeground(new java.awt.Color(255, 255, 255));
        searchButton2.setText("Search");
        searchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton2ActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(37, 24, 46));
        jLabel21.setText("Kode Kuliah :");

        jLabel22.setForeground(new java.awt.Color(37, 24, 46));
        jLabel22.setText("Nama Kuliah :");

        jLabel37.setForeground(new java.awt.Color(37, 24, 46));
        jLabel37.setText("Semester :");

        semesterEditField.setEnabled(false);

        jLabel38.setForeground(new java.awt.Color(37, 24, 46));
        jLabel38.setText("SKS :");

        UpdateKButton.setBackground(new java.awt.Color(0, 51, 255));
        UpdateKButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateKButton.setText("Update");
        UpdateKButton.setEnabled(false);
        UpdateKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateKButtonActionPerformed(evt);
            }
        });

        DeleteKButton.setBackground(new java.awt.Color(202, 31, 61));
        DeleteKButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteKButton.setText("Delete");
        DeleteKButton.setEnabled(false);
        DeleteKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteKButtonActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(37, 24, 46));
        jLabel39.setText("Traversal");

        traversalKuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Kuliah", "Nama Kuliah", "SKS", "Semester"
            }
        ));
        traversalKuliah.setEnabled(false);
        traversalKuliah.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                traversalKuliahAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(traversalKuliah);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sksEditField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaKuliahEditField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeKuliahEditField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semesterEditField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npmSearchField2))
                            .addComponent(jLabel19)
                            .addComponent(jLabel35))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateKButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteKButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                                .addComponent(jLabel39)
                                .addGap(172, 172, 172))))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(412, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(npmSearchField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton2)
                    .addComponent(UpdateKButton)
                    .addComponent(DeleteKButton))
                .addGap(14, 14, 14)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(kodeKuliahEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(namaKuliahEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sksEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Kuliah", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 190, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 24, 46));
        jLabel10.setText("Search data");

        jLabel11.setForeground(new java.awt.Color(37, 24, 46));
        jLabel11.setText("NPM :");

        jLabel12.setForeground(new java.awt.Color(37, 24, 46));
        jLabel12.setText("Nama :");

        jLabel13.setForeground(new java.awt.Color(37, 24, 46));
        jLabel13.setText("JK :");

        npmEditField.setEditable(false);
        npmEditField.setEnabled(false);

        namaEditField.setEnabled(false);

        UpdateButton.setBackground(new java.awt.Color(0, 51, 255));
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.setEnabled(false);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(37, 24, 46));
        jLabel17.setText("Result data");

        jLabel18.setForeground(new java.awt.Color(37, 24, 46));
        jLabel18.setText("NPM");

        npmSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npmSearchFieldActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(51, 153, 0));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jkEditField.setEnabled(false);

        DeleteButton.setBackground(new java.awt.Color(202, 31, 61));
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        tglLhrEditField.setEnabled(false);

        alamatEditField.setEnabled(false);

        noTelpEditField.setEnabled(false);
        noTelpEditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpEditFieldActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(37, 24, 46));
        jLabel24.setText("Tanggal Lahir :");

        jLabel25.setForeground(new java.awt.Color(37, 24, 46));
        jLabel25.setText("Nomor Telepon  :");

        jLabel26.setForeground(new java.awt.Color(37, 24, 46));
        jLabel26.setText("Alamat :");

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(37, 24, 46));
        jLabel29.setText("Traversal");

        traversalMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "NPM", "Nama", "Nilai", "HM", "Keterangan"
            }
        ));
        traversalMahasiswa.setEnabled(false);
        traversalMahasiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                traversalMahasiswaFocusGained(evt);
            }
        });
        jScrollPane4.setViewportView(traversalMahasiswa);
        if (traversalMahasiswa.getColumnModel().getColumnCount() > 0) {
            traversalMahasiswa.getColumnModel().getColumn(4).setHeaderValue("HM");
            traversalMahasiswa.getColumnModel().getColumn(5).setHeaderValue("Keterangan");
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npmSearchField))
                            .addComponent(jLabel10)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jkEditField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(namaEditField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npmEditField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglLhrEditField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(alamatEditField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(noTelpEditField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addGap(190, 190, 190))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(npmSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton)
                            .addComponent(UpdateButton)
                            .addComponent(DeleteButton))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(npmEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(namaEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jkEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tglLhrEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25))
                                    .addComponent(noTelpEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jLabel26))
                            .addComponent(alamatEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mahasiswa", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 190, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 24, 46));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Input Data Mahasiswa");

        insertInputButton.setBackground(new java.awt.Color(0, 51, 255));
        insertInputButton.setForeground(new java.awt.Color(255, 255, 255));
        insertInputButton.setText("Insert");
        insertInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertInputButtonActionPerformed(evt);
            }
        });

        resetInputButton.setBackground(new java.awt.Color(202, 31, 61));
        resetInputButton.setForeground(new java.awt.Color(255, 255, 255));
        resetInputButton.setText("Reset");
        resetInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetInputButtonActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(37, 24, 46));
        jLabel23.setText("NPM :");

        jLabel27.setForeground(new java.awt.Color(37, 24, 46));
        jLabel27.setText("Nama :");

        jLabel28.setForeground(new java.awt.Color(37, 24, 46));
        jLabel28.setText("JK :");

        jLabel30.setForeground(new java.awt.Color(37, 24, 46));
        jLabel30.setText("Nomor Telepon  :");

        jLabel40.setForeground(new java.awt.Color(37, 24, 46));
        jLabel40.setText("Alamat :");

        noTelpInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpInputFieldActionPerformed(evt);
            }
        });

        jLabel41.setForeground(new java.awt.Color(37, 24, 46));
        jLabel41.setText("Tanggal Lahir :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(insertInputButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetInputButton)
                        .addGap(354, 354, 354))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(283, 283, 283))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel23)
                    .addComponent(jLabel41)
                    .addComponent(jLabel30)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jkInputField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaInputField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npmInputField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglLhrInputField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatInputField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTelpInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(npmInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(namaInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jkInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tglLhrInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30))
                            .addComponent(noTelpInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel40))
                    .addComponent(alamatInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertInputButton)
                    .addComponent(resetInputButton))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Tambah Mahasiswa", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 190, 0));

        insertInputButton1.setBackground(new java.awt.Color(0, 51, 255));
        insertInputButton1.setForeground(new java.awt.Color(255, 255, 255));
        insertInputButton1.setText("Insert");
        insertInputButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertInputButton1ActionPerformed(evt);
            }
        });

        resetInputButton1.setBackground(new java.awt.Color(202, 31, 61));
        resetInputButton1.setForeground(new java.awt.Color(255, 255, 255));
        resetInputButton1.setText("Reset");
        resetInputButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetInputButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 24, 46));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Input Data Kuliah");

        jLabel45.setForeground(new java.awt.Color(37, 24, 46));
        jLabel45.setText("Nama Kuliah :");

        jLabel46.setForeground(new java.awt.Color(37, 24, 46));
        jLabel46.setText("Semester :");

        jLabel48.setForeground(new java.awt.Color(37, 24, 46));
        jLabel48.setText("Kode Kuliah :");

        jLabel49.setForeground(new java.awt.Color(37, 24, 46));
        jLabel49.setText("SKS :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sksInputField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaKuliahInputField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semesterInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodeKuliahInputField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(insertInputButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetInputButton1)
                        .addGap(333, 333, 333))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(kodeKuliahInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(namaKuliahInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sksInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertInputButton1)
                    .addComponent(resetInputButton1))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Tambah Kuliah", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        Koneksi kon = new Koneksi();
        ResultSet rs = null; int i = 0;
        String HM= ""; String Keterangan = "";
        rs = kon.getData("select mahasiswa.*, nilai_kuliah.* from mahasiswa inner join nilai_kuliah on mahasiswa.npm = nilai_kuliah.npm");
        try {
            while(rs.next()){
                int nilai = Integer.parseInt(rs.getString("nilai"));
                
                if(nilai >= 80 && nilai <= 100){
                    HM = "A"; Keterangan = "Lulus";
                }else if(nilai >= 68 && nilai < 80){
                    HM = "B"; Keterangan = "Lulus";
                }else if(nilai >= 55 && nilai < 68){
                    HM = "C"; Keterangan = "Lulus";
                }else if(nilai >= 45 && nilai < 55){
                    HM = "D"; Keterangan = " Tidak Lulus";
                }else if(nilai >= 0 && nilai < 45){
                    HM = "E"; Keterangan = "Tidak Lulus";
                }
                
                traversalMahasiswa.setValueAt(i+1, i, 0);
                traversalMahasiswa.setValueAt(rs.getString("npm"), i, 1);
                traversalMahasiswa.setValueAt(rs.getString("nama_mhs"), i, 2);
                traversalMahasiswa.setValueAt(rs.getString("nilai"), i, 3);
                traversalMahasiswa.setValueAt(HM, i, 4);
                traversalMahasiswa.setValueAt(Keterangan, i, 5);
                i++;
            }
            rs.close();
        } catch(Exception e){

        }
        
        rs = kon.getData("select * from nilai_kuliah");
        i = 0;
        try {
            while(rs.next()){
                traversalNilaiKuliah.setValueAt(i+1, i, 0);
                traversalNilaiKuliah.setValueAt(rs.getString("npm"), i, 1);
                traversalNilaiKuliah.setValueAt(rs.getString("kode_kul"), i, 2);
                traversalNilaiKuliah.setValueAt(rs.getString("nilai"), i, 3);
                i++;
            }
            rs.close();
        } catch(Exception e){}
        
        
        rs = kon.getData("select * from kuliah");
        i = 0;
        try {
            while(rs.next()){
                traversalKuliah.setValueAt(i+1, i, 0);
                traversalKuliah.setValueAt(rs.getString("kode_kul"), i, 1);
                traversalKuliah.setValueAt(rs.getString("nama_kul"), i, 2);
                traversalKuliah.setValueAt(rs.getString("sks"), i, 3);
                traversalKuliah.setValueAt(rs.getString("semester"), i, 4);
                i++;
            }
            rs.close();
        } catch(Exception e){}
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from mahasiswa where npm = '"+npmSearchField.getText()+"'");
            while(rs.next()){
                npmEditField.setText(rs.getString("npm"));
                namaEditField.setText(rs.getString("nama_mhs"));
                jkEditField.setText(rs.getString("jenis_kelamin"));
                tglLhrEditField.setText(rs.getString("tgl_lahir"));
                noTelpEditField.setText(rs.getString("no_telp"));
                alamatEditField.setText(rs.getString("alamat"));
                javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                namaEditField.setEnabled(true);
                jkEditField.setEnabled(true);
                tglLhrEditField.setEnabled(true);
                noTelpEditField.setEnabled(true);
                alamatEditField.setEnabled(true);
                UpdateButton.setEnabled(true);
                DeleteButton.setEnabled(true);
            }
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void npmSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmSearchFieldActionPerformed

    }//GEN-LAST:event_npmSearchFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        Mahasiswa peg = new Mahasiswa();
        peg.setNPM(npmEditField.getText());
        peg.setNama(namaEditField.getText());
        peg.setJK(jkEditField.getText());
        peg.setTglLahir(tglLhrEditField.getText());
        peg.setNoTelp(Integer.parseInt(noTelpEditField.getText()));
        peg.setAlamat(alamatEditField.getText());
        peg.updateMahasiswa();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonNKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonNKActionPerformed
        // TODO add your handling code here:
//        Nilai_Kuliah peg = new Nilai_Kuliah();
//        peg.setNPM(npmNKEditField.getText());
//        peg.setKodeKuliah(kodeKuliahNKEditField.getText());
//        peg.setNilai(Integer.parseInt(nilaiNKEditField.getText()));
//        peg.updateNilai();
        
        JOptionPane.showMessageDialog(null, "Apakah anda yakin akan menghapus?");
        kodeKuliahNKEditField.setEnabled(false); 
        nilaiNKEditField.setEnabled(false);
        Nilai_Kuliah peg = new Nilai_Kuliah();
        peg.setNPM(npmNKEditField.getText());
        peg.setKodeKuliah(kodeKuliahNKEditField.getText());
        peg.setNilai(Integer.parseInt(nilaiNKEditField.getText()));
        peg.deleteNilai();
        JOptionPane.showMessageDialog(null, "Delete Success");
        npmEditField.setText(null);
        namaEditField.setText(null);
        jkEditField.setText(null);
    }//GEN-LAST:event_DeleteButtonNKActionPerformed

    private void npmSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npmSearchField1ActionPerformed

    
    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from nilai_kuliah where npm = '"+npmSearchField1.getText()+"'" + "and kode_kul = '" + KKSearchField.getText()+"'");
            while(rs.next()){
                npmNKEditField.setText(rs.getString("npm"));
                kodeKuliahNKEditField.setText(rs.getString("kode_kul"));
                nilaiNKEditField.setText(rs.getString("nilai"));
                javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                kodeKuliahNKEditField.setEnabled(true);
                nilaiNKEditField.setEnabled(true);
                DeleteButtonNK.setEnabled(true);
                UpdateButtonNK.setEnabled(true);
            }
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void npmSearchField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmSearchField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npmSearchField2ActionPerformed

    private void searchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton2ActionPerformed
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from kuliah where kode_kul = '"+npmSearchField2.getText()+"'");
            while(rs.next()){
                kodeKuliahEditField.setText(rs.getString("kode_kul"));
                namaKuliahEditField.setText(rs.getString("nama_kul"));
                sksEditField.setText(rs.getString("sks"));
                semesterEditField.setText(rs.getString("semester"));
                javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                namaKuliahEditField.setEnabled(true);
                sksEditField.setEnabled(true);
                semesterEditField.setEnabled(true);
                UpdateKButton.setEnabled(true);
                DeleteKButton.setEnabled(true);
            }
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_searchButton2ActionPerformed

    private void npmNKEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmNKEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npmNKEditFieldActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Apakah anda yakin akan menghapus?");
        Mahasiswa peg = new Mahasiswa();
        Nilai_Kuliah nilai = new Nilai_Kuliah();
        nilai.setNPM(npmEditField.getText());
        peg.setNPM(npmEditField.getText());
        peg.setNama(namaEditField.getText());
        peg.setJK(jkEditField.getText());
        peg.setTglLahir(tglLhrEditField.getText());
        peg.setNoTelp(Integer.parseInt(noTelpEditField.getText()));
        peg.setAlamat(alamatEditField.getText());
        nilai.deleteNilai();
        peg.deleteMahasiswa();
        JOptionPane.showMessageDialog(null, "Delete Success");
        npmEditField.setText(null);
        namaEditField.setText(null);
        jkEditField.setText(null);
        tglLhrEditField.setText(null);
        noTelpEditField.setText(null);
        alamatEditField.setText(null);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void noTelpEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpEditFieldActionPerformed

    private void UpdateButtonNKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonNKActionPerformed
        // TODO add your handling code here:
        Nilai_Kuliah peg = new Nilai_Kuliah();
        peg.setNPM(npmNKEditField.getText());
        peg.setKodeKuliah(kodeKuliahNKEditField.getText());
        peg.setNilai(Integer.parseInt(nilaiNKEditField.getText()));
        peg.updateNilai();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
    }//GEN-LAST:event_UpdateButtonNKActionPerformed

    private void UpdateKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateKButtonActionPerformed
        // TODO add your handling code here:
        Kuliah peg = new Kuliah();
        peg.setKode_Kul(kodeKuliahEditField.getText());
        peg.setNama_Kul(namaKuliahEditField.getText());
        peg.setSks(sksEditField.getText());
        peg.setSemester(semesterEditField.getText());
        peg.updateKuliah();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
    }//GEN-LAST:event_UpdateKButtonActionPerformed

    private void DeleteKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteKButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Apakah anda yakin akan menghapus?");
        Kuliah peg = new Kuliah();
        peg.setKode_Kul(kodeKuliahEditField.getText());
        peg.setNama_Kul(namaKuliahEditField.getText());
        peg.setSks(sksEditField.getText());
        peg.setSemester(semesterEditField.getText());
        peg.deleteKuliah();
        javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");
    }//GEN-LAST:event_DeleteKButtonActionPerformed

    private void insertInputButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertInputButton1ActionPerformed
        // TODO add your handling code here:
        Kuliah peg = new Kuliah();
        peg.setKode_Kul(kodeKuliahInputField.getText());
        peg.setNama_Kul(namaKuliahInputField.getText());
        peg.setSks(sksInputField.getText());
        peg.setSemester(semesterInputField.getText());
        peg.insertKuliah();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");
        kodeKuliahInputField.setText(null);
        namaKuliahInputField.setText(null);
        sksInputField.setText(null);
        semesterInputField.setText(null);
    }//GEN-LAST:event_insertInputButton1ActionPerformed

    private void resetInputButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetInputButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetInputButton1ActionPerformed

    private void traversalKuliahAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_traversalKuliahAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_traversalKuliahAncestorAdded

    private void traversalMahasiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_traversalMahasiswaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_traversalMahasiswaFocusGained

    private void noTelpInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpInputFieldActionPerformed

    private void resetInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetInputButtonActionPerformed
        npmInputField.setText(null);
        namaInputField.setText(null);
        jkInputField.setText(null);
        tglLhrInputField.setText(null);
        noTelpInputField.setText(null);
        alamatInputField.setText(null);
    }//GEN-LAST:event_resetInputButtonActionPerformed

    private void insertInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertInputButtonActionPerformed
        Mahasiswa peg = new Mahasiswa();
        peg.setNPM(npmInputField.getText());
        peg.setNama(namaInputField.getText());
        peg.setJK(jkInputField.getText());
        peg.setTglLahir(tglLhrInputField.getText());
        peg.setNoTelp(Integer.parseInt(noTelpInputField.getText()));
        peg.setAlamat(alamatInputField.getText());
        peg.insertMahasiswa();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");
        npmInputField.setText(null);
        namaInputField.setText(null);
        jkInputField.setText(null);
        tglLhrInputField.setText(null);
        noTelpInputField.setText(null);
        alamatInputField.setText(null);
    }//GEN-LAST:event_insertInputButtonActionPerformed

    private void insertInputNKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertInputNKButtonActionPerformed
        // TODO add your handling code here:
        Nilai_Kuliah peg = new Nilai_Kuliah();
        peg.setNPM(npmNKInputField.getText());
        peg.setKodeKuliah(kodeKuliahNKInputField.getText());
        peg.setNilai(Integer.parseInt(nilaiNKInputField.getText()));
        peg.insertNilai();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");
    }//GEN-LAST:event_insertInputNKButtonActionPerformed

    private void resetInputNKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetInputNKButtonActionPerformed
        // TODO add your handling code here:
        npmNKInputField.getText();
        kodeKuliahNKInputField.getText();
        nilaiNKInputField.getText();
    }//GEN-LAST:event_resetInputNKButtonActionPerformed

    private void kodeKuliahNKInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeKuliahNKInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeKuliahNKInputFieldActionPerformed

    private void KKSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KKSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KKSearchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteButtonNK;
    private javax.swing.JButton DeleteKButton;
    private javax.swing.JTextField KKSearchField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UpdateButtonNK;
    private javax.swing.JButton UpdateKButton;
    private javax.swing.JTextField alamatEditField;
    private javax.swing.JTextField alamatInputField;
    private javax.swing.JButton insertInputButton;
    private javax.swing.JButton insertInputButton1;
    private javax.swing.JButton insertInputNKButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jkEditField;
    private javax.swing.JTextField jkInputField;
    private javax.swing.JTextField kodeKuliahEditField;
    private javax.swing.JTextField kodeKuliahInputField;
    private javax.swing.JTextField kodeKuliahNKEditField;
    private javax.swing.JTextField kodeKuliahNKInputField;
    private javax.swing.JTextField namaEditField;
    private javax.swing.JTextField namaInputField;
    private javax.swing.JTextField namaKuliahEditField;
    private javax.swing.JTextField namaKuliahInputField;
    private javax.swing.JTextField nilaiNKEditField;
    private javax.swing.JTextField nilaiNKInputField;
    private javax.swing.JTextField noTelpEditField;
    private javax.swing.JTextField noTelpInputField;
    private javax.swing.JTextField npmEditField;
    private javax.swing.JTextField npmInputField;
    private javax.swing.JTextField npmNKEditField;
    private javax.swing.JTextField npmNKInputField;
    private javax.swing.JTextField npmSearchField;
    private javax.swing.JTextField npmSearchField1;
    private javax.swing.JTextField npmSearchField2;
    private javax.swing.JButton resetInputButton;
    private javax.swing.JButton resetInputButton1;
    private javax.swing.JButton resetInputNKButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JButton searchButton2;
    private javax.swing.JTextField semesterEditField;
    private javax.swing.JTextField semesterInputField;
    private javax.swing.JTextField sksEditField;
    private javax.swing.JTextField sksInputField;
    private javax.swing.JTextField tglLhrEditField;
    private javax.swing.JTextField tglLhrInputField;
    private javax.swing.JTable traversalKuliah;
    private javax.swing.JTable traversalMahasiswa;
    private javax.swing.JTable traversalNilaiKuliah;
    // End of variables declaration//GEN-END:variables
}
